spring.application.name=employee-management-system

# Logging to file
logging.file.name=logs/employee-app.log

# Log level
logging.level.root=INFO
logging.level.com.amar.ems=DEBUG

# MySQL Configuration
spring.datasource.url=jdbc:mysql://mysql-db:3306/ems_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true